service: cvs-svc-defect

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  getDefects:
    handler: src/handler.handler
    events:
    - http:
        path: defects
        method: get

custom:
  serverless-offline:
    port: 3001
  dynamodb:
    start:
      port: 8001
      inMemory: true
      migrate: true
      seed: false
    seed:
      seed_name:
        sources:
          - table: cvs-local-defects
            sources: [./tests/resources/defects.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-defects
        AttributeDefinitions:
        - AttributeName: imNumber
          AttributeType: N
        KeySchema:
        - AttributeName: imNumber
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
